-- 1. 테이블 생성
CREATE TABLE JOB_INFO(
    JOB_ID  VARCHAR(10),
    MIN_SALARY NUMBER,
    MAX_SALARY NUMBER
);

-- 자료 삽입
INSERT INTO JOB_INFO VALUES ('AD_PRES', 20080, 40000);
INSERT INTO JOB_INFO VALUES ('AD_VP', 15000, 30000);
INSERT INTO JOB_INFO VALUES ('AD_ASST', 3000, 6000);
INSERT INTO JOB_INFO VALUES ('AD_MGR', 8200, 16000);
INSERT INTO JOB_INFO VALUES ('AD_ACCOUNT', 4200, 9000);
INSERT INTO JOB_INFO VALUES ('AD_MGR', 8200, 16000);
INSERT INTO JOB_INFO VALUES ('AD_ACCOUNT', 4200, 9000);

SELECT * FROM JOB_INFO;

-- 2. 뷰(VIEW) 생성
-- 최저 급여가 5000 달러 이상인 직업 아이디를 검색한 뷰 생성
CREATE VIEW V_JOB_INFO
AS SELECT * 
   FROM JOB_INFO
   WHERE MIN_SALARY > 5000;

-- 뷰 검색
SELECT * FROM V_JOB_INFO;

-- 직업 아이디의 이름이 MGR로 끝나는 자료 검색
SELECT * FROM V_JOB_INFO WHERE JOB_ID LIKE '%MGR';









